SortWasteVictoria-WebApp/Controllers/GarbagesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SortWasteVictoria_WebApp.Data;
using SortWasteVictoria_WebApp.Models;

namespace SortWasteVictoria_WebApp.Controllers
{
    public class GarbagesController : Controller
    {
        private readonly SortWasteVictoria_WebAppContext _context;

        public GarbagesController(SortWasteVictoria_WebAppContext context)
        {
            _context = context;
        }

        // GET: Garbages
        public async Task<IActionResult> Index()
        {
            var sortWasteVictoria_WebAppContext = _context.Garbage.Include(g => g.Bin);
            return View(await sortWasteVictoria_WebAppContext.ToListAsync());
        }

        //GET: Garbages/Info
/*        public async Task<IActionResult> Info(string SearchString)
        {
            var sortWasteVictoria_WebAppContext = _context.Garbage.Include(g => g.Bin);

            ViewData["CurrentFilter"] = SearchString;
            //var garbages = from g in _context.Garbage select g;

            List<Garbage> garbageList = sortWasteVictoria_WebAppContext.ToList();

            Garbage test = new Garbage();
            Bin testBin = new Bin();
            testBin.BinColour = "test";
            test.GarbageName = SearchString;
            test.Bin = testBin;
            var testList = new List<Garbage>();
            testList.Add(test);

            if (!garbageList.Contains(test))
            {              
                List < Garbage > found = garbageList.Where(gb => gb.GarbageName.Contains(SearchString)).ToList();

                return View(found); 
            }
            else
            { 
                return View(testList); 
            }
        }*/

        public async Task<IActionResult> Info(string SearchString)
        {
            var sortWasteVictoria_WebAppContext = _context.Garbage.Include(g => g.Bin);

            ViewData["CurrentFilter"] = SearchString;
            List<Garbage> garbageList = sortWasteVictoria_WebAppContext.ToList();
            if (garbageList.Any(g => g.GarbageName.Contains(SearchString)))
            {
                List<Garbage> found = garbageList.Where(gb => gb.GarbageName.Contains(SearchString)).ToList();
                return View(found);
            }
            else
            {
                List<Garbage> notFound = new List<Garbage>();
                return View(notFound);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Search()
        {
            string prefix = HttpContext.Request.Query["term"].ToString();
            var garbages = _context.Garbage.Where(g => g.GarbageName.Contains(prefix))
                     .Select(g => g.GarbageName).ToList();
            return Ok(garbages);
            /* try
             {
                 string prefix = HttpContext.Request.Query["prefix"].ToString();
                 var garbages = _context.Garbage.Where(g => g.GarbageName.Contains(prefix))
                     .Select(g => g.GarbageName).ToList();
                 return Ok(garbages);
             }
             catch
             {
                 return BadRequest();
             }*/
        }



        // GET: Garbages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Garbage == null)
            {
                return NotFound();
            }

            var garbage = await _context.Garbage
                .Include(g => g.Bin)
                .FirstOrDefaultAsync(m => m.GarbageId == id);
            if (garbage == null)
            {
                return NotFound();
            }

            return View(garbage);
        }

        // GET: Garbages/Create
        public IActionResult Create()
        {
            ViewData["BinId"] = new SelectList(_context.Bin, "BinId", "BinId");
            return View();
        }

        // POST: Garbages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GarbageId,GarbageName,BinId")] Garbage garbage)
        {
            if (ModelState.IsValid)
            {
                _context.Add(garbage);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BinId"] = new SelectList(_context.Bin, "BinId", "BinId", garbage.BinId);
            return View(garbage);
        }

        // GET: Garbages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Garbage == null)
            {
                return NotFound();
            }

            var garbage = await _context.Garbage.FindAsync(id);
            if (garbage == null)
            {
                return NotFound();
            }
            ViewData["BinId"] = new SelectList(_context.Bin, "BinId", "BinId", garbage.BinId);
            return View(garbage);
        }

        // POST: Garbages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GarbageId,GarbageName,BinId")] Garbage garbage)
        {
            if (id != garbage.GarbageId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(garbage);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GarbageExists(garbage.GarbageId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BinId"] = new SelectList(_context.Bin, "BinId", "BinId", garbage.BinId);
            return View(garbage);
        }

        // GET: Garbages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Garbage == null)
            {
                return NotFound();
            }

            var garbage = await _context.Garbage
                .Include(g => g.Bin)
                .FirstOrDefaultAsync(m => m.GarbageId == id);
            if (garbage == null)
            {
                return NotFound();
            }

            return View(garbage);
        }

        // POST: Garbages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Garbage == null)
            {
                return Problem("Entity set 'SortWasteVictoria_WebAppContext.Garbage'  is null.");
            }
            var garbage = await _context.Garbage.FindAsync(id);
            if (garbage != null)
            {
                _context.Garbage.Remove(garbage);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GarbageExists(int id)
        {
          return (_context.Garbage?.Any(e => e.GarbageId == id)).GetValueOrDefault();
        }
    }
}

SortWasteVictoria-WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SortWasteVictoria_WebApp.Models;
using System.Diagnostics;

namespace SortWasteVictoria_WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult InformationPage() 
        { 
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SortWasteVictoria-WebApp/Views/Home/Index.cshtml
@model IEnumerable<SortWasteVictoria_WebApp.Models.Garbage>

@{
    ViewData["Title"] = "Home Page";
}

<br />
<div class="text-center">
    <h1 class="display-4" style="color: #388087; font-size:70px"><b>Welcome to Sort Waste Victoria</b></h1>
    <p style="font-size:30px;">We will help you sort your waste!</p>
    
</div>

<br/>

<div class="text-center">
    <form asp-controller="Garbages" asp-action="Info">
        @*<p>Please enter a waste item below:</p>*@
        <p>Search for an item below and see which bin to use!</p>
        <p>
            <input type="text" id="garbageName" name="SearchString" value="@ViewData["CurrentFilter"]"/>
            <input type="submit" value="Search" class="button"/>
        </p>
    </form>
</div>
<style>
    .button{
        background-color:#C2EDCE;
        padding:10px 16px;
        border-radius: 25px;
    }
</style>

<br />

<div class="content">
    <p class="text-center">
        The correct disposal of waste is crucial for the sustainability of our planet.
        By using color-coded bins for different types of waste,
        such as green for organic waste, yellow for recyclables etc,
        we can help ensure that each material is processed in the most environmentally friendly way possible.
        Remember, every small action counts towards a cleaner and greener future!
    </p>
</div>
<style>
    .content {
        max-width: 750px;
        margin: auto;
    }
</style>

@section Scripts{
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(function () {            
            $("#garbageName").autocomplete({
                source: '/Garbages/Search'                  
            });
        });
    </script>
}


@*<div>
    <h2>You have chosen : @Html.DisplayFor(model => model)</h2>
    <p>Bin Number: @Html.DisplayFor(modelItem => item.Bin.BinId)</p>
</div>*@

SortWasteVictoria-WebApp/Views/Home/InformationPage.cshtml
@{
    ViewData["Title"] = "General Sorting Information";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .row {
        border-bottom: 1px solid #ccc;
        padding-bottom: 20px;
        margin-bottom: 20px;
    }

    h2 {
        margin-top: 70px;
    }
</style>

<h1 class="text-center" style="margin-bottom: 20px">General Sorting Information</h1>

<div class="row">
    <div class="col-md-6">
        <img src="https://drive.google.com/uc?export=view&id=100GYO3GWmXBjgCgjOZSAPaflpRunpDjB" alt="Purple Bins" width="400" height="600" />
    </div>
    <div class="col-md-6">
        <img src="https://drive.google.com/uc?export=view&id=10zD1Z8ETiKQXAFy0WHMYDC1bXOe64H2j" alt="Purple Bins Yes" width="500" height="200" style="margin-top: 70px;" />
        </br>
        <img src="https://drive.google.com/uc?export=view&id=10yCOIeF3GR3LZ6VvwvFenTZtn1D45eC3" alt="Purple Bins No" width=500" height="200" style="margin-top: 20px; margin-bottom: 20px;" />
        <p>Collection Routine: Every <b>four</b> weeks.</p>
    </div>
</div>

<div class="row">
    <div class="col-md-6 order-md-2">
        <div class="text-center">
            <img src="https://drive.google.com/uc?export=view&id=1043VfiPwJBzUfhEDtYnjvV5snEdPjoW3" alt="Green Bins" width="400" height="600" />
        </div>
    </div>
    <div class="col-md-6 order-md-1">
        <img src="https://drive.google.com/uc?export=view&id=10llKHZL6DjN1mTjsxpoV0Qqfnqi6SI0y" alt="Green Bins Yes" width="500" height="200" style="margin-top: 70px;" />
        </br>
        <img src="https://drive.google.com/uc?export=view&id=11-g8aHjFCoib7HLUyLHMP4K1weyK13gQ" alt="Green Bins No" width=500" height="200" style="margin-top: 20px; margin-bottom: 20px;" />
        <p>Collection Routine: <b>Weekly</b> in urban areas. <b>Fortnightly</b> in rural areas.</p>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <img src="https://drive.google.com/uc?export=view&id=1-rQg-ve_U_9Ib0IGIRURitxTfc4m7EEB" alt="Yellow Bins" width="400" height="600" />
    </div>
    <div class="col-md-6">
        <img src="https://drive.google.com/uc?export=view&id=10pWGyBghcPrGlO0Lg_aDCOq6Y7jygI3t" alt="Yellow Bins Yes" width="500" height="200" style="margin-top: 70px;" />
        </br>
        <img src="https://drive.google.com/uc?export=view&id=10nAaQai4Evk-rQ2ZUHtrkMSlO3d6ala5" alt="Yellow Bins No" width=500" height="200" style="margin-top: 20px; margin-bottom: 20px;" />
        <p>Collection Routine:<b> Fortnightly</b></p>
    </div>
</div>

<div class="row">
    <div class="col-md-6 order-md-2">
        <div class="text-center">
            <img src="https://drive.google.com/uc?export=view&id=1-yXSn7TtqPzBW342tf5TU4Swlfk1MnvS" alt="Red Bins" width="400" height="600" />
        </div>
    </div>
    <div class="col-md-6 order-md-1">
        <img src="https://drive.google.com/uc?export=view&id=10vFTn2Lxr8GVYJJQkt_tui7sham2LgV9" alt="Red Bins Yes" width="500" height="200" style="margin-top: 70px;" />
        </br>
        <img src="https://drive.google.com/uc?export=view&id=10tTGCV1JXDgzbCMcOnnQFSgKnrVgEwFq" alt="Red Bins No" width=500" height="200" style="margin-top: 20px; margin-bottom: 20px;" />
        <p>Collection Routine:<b> Fortnightly</b></p>
    </div>
</div>

<div class="row">
    <p>All Information and Images are gathered from:</p>
    <div class="col-md-6">
        <div class="text-center">
            <a href="https://www.mitchellshire.vic.gov.au/news/our-bins-are-changing">
                <div style="display: flex; align-items: center; justify-content: center; height: 100px; cursor: pointer;">
                    <div style="padding: 5px;">
                        <h3 style="margin-top: 0;">Our Bins Are Changing</h3>
                        <p>Mitchell Shire Council</p>
                    </div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-md-6">
        <div class="text-center">
            <a href="https://www.surfcoast.vic.gov.au/Property/Waste-and-recycling/Bins">
                <div style="display: flex; align-items: center; justify-content: center; height: 100px; cursor: pointer;">
                    <div style="padding: 5px;">
                        <h3 style="margin-top: 0;">Waste and Reclying Bins</h3>
                        <p>Surfcoast Shire</p>
                    </div>
                </div>
            </a>
        </div>
    </div>
</div>